version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=dev
            - DB_HOST=db
            - DB_PORT=5432
        # volumes:
        #     - ./src:/app/src
        depends_on:
            - db
        restart: always
    db:
        image: postgres
        env_file:
            - ./.env
        ports:
            - 5433:5432
        restart: always
    docs:
        build:
            context: ./apidoc
            dockerfile: ./Dockerfile
        volumes:
            - ./server/src:/app/src
        ports:
            - 8082:5000
        restart: always

